framework:
  messenger:
    transports:
      async_priority_high: '%env(MESSENGER_TRANSPORT_DSN_AMQP)%'
      async_priority_normal:
        dsn: "%env(MESSENGER_TRANSPORT_DSN_DOCTRINE)%"
        options:
          queue_name: normal_priority
      async_priority_low: '%env(MESSENGER_TRANSPORT_DSN_REDIS)%'

    routing:
      # Route your messages to the transports
      'App\Message\UserRegistration': async_priority_high
      'App\Message\Game\GameCreated': async_priority_high
      'App\Message\Game\GameUpdated': async_priority_high
